### ISSUE TITLE
automatic id column

### ISSUE THREAD

**Issue by mixflame** [mixflame/SwissDB#15]
Make sure an id column is created if there is not one specified.

**Comment by KCErb** [comment]
OK, after looking into this a bit let's discuss.

From [what](https://www.sqlite.org/autoinc.html) [I read](http://stackoverflow.com/questions/8246649/why-cant-you-use-sqlite-rowid-as-a-primary-key), SQLite has a default ROWID column that autoincrements and everything.

We would use this as the primary key and call it by 'id' like so

``` ruby
add_column('id', "INTEGER PRIMARY KEY")
```

but [some folks say this is a bad idea](http://www.sqlabs.com/blog/2010/12/sqlite-and-unique-rowid-something-you-really-need-to-know/) reasoning that because row ids get cleaned up when you vacuum the database they can get corrupted.

So how do we want to do this?

I lean towards ignoring the SQLite docs and creating and autoincrementing integer column called id. Period.
- If the user tries to include an integer column called id we ignore it because we already have one.
- If the user tries to create a column called "id" with a different type we warn them that it won't get created.
- If they specify a different primary key we use that, but they still get the integer column.

What do you think? What's the best practice here?

**Comment by mixflame** [comment]
Hey KC.

I agree with everything you said I think.

I think this part of that article is the meat.

From the official documentation: “Rowids can change at any time and without
notice. If you need to depend on your rowid, make it an INTEGER PRIMARY
KEY, then it is guaranteed not to change”. And I add also AUTOINCREMENT so
you are sure that the same rowid(s) are not reused when rows are deleted.

If we do everything you said, and make sure to set PRIMARY KEY and possibly
AUTOINCREMENT (if an integer) on the actual ID and primary column we
declare, we should be fine. I think you have the right idea here. I didn't
disagree with anything.

Thanks.

**Comment by KCErb** [comment]
closed via [PR#21](https://github.com/jsilverMDX/SwissDB/pull/21)
