### ISSUE TITLE
Cleaner execution context

### ISSUE THREAD

**Issue by KCErb** [mixflame/SwissDB#22]
When I was playing around with the codebase today I realized something I hadn't realized before: we're defining all of our db methods that schema uses on `Object`. I'd like to see if I can come up with a cleaner context for those methods so that we don't give every object our database methods. Seems dangerous!

**Comment by mixflame** [comment]
You are correct. This is not desirable. I am almost certain CoreDataQuery
doesn't do this. We should find out what they do and attempt to do it. The
methods being there pollutes the namespace and now nobody can have a method
called "entity" on any object. We do need to find a way around this as soon
as possible. :D It will make us look a lot better. For the simple hack that
it started as, this works. But you're right. It's not production
architecture (yet).

**Comment by mixflame** [comment]
I just made progress in making it work for me. I noticed schema.rb has to be called that now and I simplified building the gem. It doesn't unnecessarily load the motion namespace anymore (when building the gem.) Also noticed just typing "rake" won't build the sql. Have to change that since "rake" is a shortcut to using the emulator and is equivelent to a build. I'm working on it though.

**Comment by mixflame** [comment]
I like what we have in dsl_context branch. No more work should need to be done here. Nice job!
